### ISSUE TITLE
Please update your module version to Minecraft 1.20!

### ISSUE THREAD

**Issue by surfishs** [Crec0/map-in-slot#3]
Please update your module version to Minecraft 1.20!

**Comment by jason-green-io** [comment]
Yes, this, please. I have an idea to play card games on an SMP running on 1.20.1, would love to try this out using this mod.

**Comment by Crec0** [comment]
Hey, I just updated the mod to 1.20. Sorry for the massive delay, I was having skill issues with rendering the map in 1.20 since mojang changed a lot about how rendering works. You guys can grab the [version 3.0.0](https://modrinth.com/mod/map-in-slot/version/3.0.0) from modrinth. It should work with any 1.20
